### ISSUE TITLE
Can't log in (Suspicious Login Attempt error)

### ISSUE THREAD

**Issue by N3pp** [a1phat0ny/instascrape#5]
https://pastebin.com/iDDhLpAu (sorry couldn't properly format it in Github for some reason)

In browser it shows the Suspicious Login Attempt screen, I assure Instagram that it's me but I get the same error everytime I try to login through InstaScrape. Once it sent me a "Verify Your Account" email with a code, I verified it and still nothing. 2FA is disabled.

**Comment by a1phat0ny** [comment]
Hi @N3pp,

I think this is more like a problem caused by a feature of Instagram rather than a bug of **InstaScrape**. Every time you log into Instagram with an unfamiliar device or session (it's **InstaScrape** in this case), Instagram needs the user to verify themselves and authorize the access (`checkpoint_required`).

The reason why you cannot log in is probably that InstaScrape tries to log in with a fresh new session every time, but the verification only affects the last session.

Currently, **InstaScrape** does not support this kind of login. However, it's hard for me to implement this feature since I don't have this problem so I cannot reproduce the error that you encountered. Anyways, I'll try my best. Thanks for your support!

**Comment by a1phat0ny** [comment]
Instascrape v2.0.0 has just released! I added support for authentication with checkpoint challenge solving in this release. Please try it out!
Thanks for your support!
